server:
  servlet:
    context-path: /api
    encoding:
      force: true
      charset: UTF-8
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: test
    url: jdbc:h2:~/test;MODE=MySQL;DATABASE_TO_LOWER=TRUE;NON_KEYWORDS=USER
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql
      encoding: utf-8
      mode: always
  main:
    banner-mode: off
    log-startup-info: false

my.error.path: classpath:my-error.json